
# Components of a program

```{r, fig.align='center', out.width="100%", echo = FALSE, fig.alt= "Major point!! example image"}
ottrpal::include_slide("https://docs.google.com/presentation/d/1YmwKdIy9BeQ3EShgZhvtb3MgR8P6iDX4DfFD65W_gdQ/edit#slide=id.gcc4fbee202_0_141")
```

## Step 1: Non profit partners

A good DataTrail program needs to be rooted in a connection to the community it wishes to serve. The DataTrail program needs to respond to what the community wants and the needs they describe.

The role of the non-profit partner is to help with the social support and resources for the scholar's development.
For example, in the Baltimore, the inaugural cohorts were done in partnership with the Youth Opportunity program of the Baltimore Mayor's office:

> Youth Opportunity (YO) Baltimore serves youth between the ages of 18 and 24 who are disconnected from school and/or the workforce and links them to community-based educational, workforce preparation, and personal development services. Operating out of two safe, youth-friendly centers – one in West Baltimore and one in East Baltimore – YO embraces a youth development model that builds upon the existing strengths of each YO member, connects them with caring adults, and offers a full range of beneficial services.

A great non profit partner is one that has overlapping goals with DataTrail in a way that you can support each other.
You may need to ask around in your community to find groups who are doing similar work.

### Tips for finding non-profit partners:

TODO: I have no idea how this is done.

## Step 2: Finding funding

You'll need funding to start your own DataTrail program. Foundations, Philanthropic organizations, and Grant giving institutions can help you secure this funding.

A DataTrail costs include:

- A program administrators time
- A case manager's time
- An lead instructor's time
- Tutor(s) time - 2 students per tutor
- Chromebook per student (~$650)
- Stipends per student during the instruction (~$4200)

### Tips for securing funding:

TODO: I have no idea how this is done.

## Step 3: Finding staff

Finding a passionate and reliable staff to run a DataTrail program is a key step to ensuring success. Ideally all the people you include on your DataTrail team have a key understanding of the goals and motivation of this program.

The number of hours that each of the positions are needed for will be dependent on the number of scholars that you run each year (and this will likely be determined by funding availability). If you run one small cohort a year, then all of these positions could be part-time or paid effort percentages of someone's time in an academic setting. However, if you secure the funding to do so, you could definitely increase the hours of each of these team members to the point that these roles could be full time positions year round.

It is advisable that these individuals generally be located in the same geographic location and for paperwork purposes, employed by the same institution (cross institutional funding mechanisms may result in overhead fees and administrative headaches).

### Program administrator

The program administrator ensures all the many pieces administration that are required to keep the DataTrail program are managed. This means managing finances as well as partnerships with community non profits and funders and internship locations.

```
General summary/purpose:

The program administrator's role is to oversee the program components and ensure their continued progress. It is their job to negotiate partnerships with the non profit community partners and coordinate and manage the DataTrail staff.  They ensure that everyone is compensated: both staff and scholars in the program.

Hours per week: 20 - 25

Specific duties & responsibilities:  

- Maintain and manage the financial budget for DataTrail program.
- Negotiate partnerships with the non profit community partners.
- Manage relationships with internship locations for DataTrail scholars upon graduation
- Assist with funding requests to philanthropic.
- Coordinate and manage the DataTrail staff.
- Set up and maintain payroll for the staff of DataTrail.
- Set up and maintain the payroll for the scholars of the DataTrail program (this will likely be coordinated through a non profit partnerships).
- Experience with financial and other types administration.
```

### Case Manager

The case manager role is crucial for the support of the DataTrail scholars and mitigating any barriers that may arise. The case manager's main responsibility is to help the scholars look ahead to see what barriers they may encounter and cooperatively figure out a plan for how the scholar can combat these barriers.

The case manager has a working relationship with the lead instructor in regards to office hours attendance and negotiating reasonable accommodations for students in regard to their course completion and assignments if/when a situation calls for it.
```
General summary/purpose:

The case manager will maintain a caseload of DataTrail scholars at various stages of course completion (enrolled, at-risk, or reinstated), as well as scholars on leave, and program alumni in an effort to stabilize retention and proactively anticipate and address the needs of those with concerns of physical and/or mental health, housing and food security, finances, and social adjustment that may affect their performance and other aspects of their DataTrail experience. The case manager will utilize a variety of interventions, referrals and follow-up services that best address scholar and alumni needs.

This position will serve as the primary resource for scholars who are on leave from DataTrail by maintaining regular communication and subsequently offering support, resources and mentoring upon the scholar’s return to DataTrail. While strong, supportive relationships may develop with scholars, the case manager does not engage in individual therapeutic relationships.

Hours per week: 15 - 20

Specific duties & responsibilities:  

- Conduct intake assessments with each incoming scholar to highlight potential areas of concern and develop an individual success plan based on their unique circumstances. Meet 1:1 thereafter to track progress towards their personal, academic and professional goals.
- Collect, document and evaluate details of scholars’ cases as reported by the scholar, DataTrail tutors, program manager and [Non profit partner].
- Formulate intervention plans in order to enhance the academic and professional success of scholars.
- Contact and collaborate with other YO and other community agencies to expedite resolution of problems.
- Provide referrals to support services with YO and other community agencies.
- Schedule regular follow-up communications with scholars on leave to determine if and when they are fit to return.
- Facilitate reinstatement of any scholars on leave who wish to return to DataTrail.
- Develop and implement an action plan to stabilize and increase scholar retention rates per enrolled cohort.
```

### Lead instructor

This person likely should have experience in the field of data science and an interest in education. Their main responsibilities are leading the office hours that are held each week and they may also assist in the one on one tutoring sessions for a subset of the scholars.

The lead instructor should have a working relationship with the program administrator, case manager, and tutors to make sure that the students are supported scholastically. Their job is to take the temperature of the cohort as it pertains to the curriculum. The office hours sessions may include a short group interactive activity but mostly open time for scholars to ask questions that may have arisen from their individual work throughout the week.

The lead instructor and the tutors both may answer asynchronous questions from the students as well.
```
General summary/purpose:

This individual will take a lead and active role in teaching within the DataTrail program https://www.datatrail.org/ Their primary responsibility will be ensuring the scholastic progress of the DataTrail scholars. We are looking for an individual with extensive teaching experience with young professionals like those in our program. Must have experience with R and some knowledge of data science.

Hours per week: 10 - 15

Specific duties & responsibilities:

- Teach data science in the form of office hours and lectures for our DataTrail students.
- Host weekly one on one tutoring sessions with our students.
- Coordinate with the program administrator and tutors to help coordinate the support the DataTrail students
- Attend weekly DataTrail team meetings
- Willing to build up programming/data science knowledge as needed for teaching our DataTrail scholars.
- Familiarity with R required.
- Familiarity with GitHub preferred.
```

### Tutors

Tutors should be individuals with data science field experience. It may be a good strategy to look for graduate students in statistics or computer science who know the basics in data science. The tutors' responsibilities are to assist the lead instructor for making sure scholars are on track and assist with questions and troubleshooting. Tutors and the lead instructor each partner with a subset of the students and meet with them 1:1 to assist with their data science questions and foster an open line for communication for their data science topics or career-related questions.  

```
General summary/purpose:

This contracted position will take an active role in teaching within the DataTrail program https://www.datatrail.org/  We are looking for an individual with extensive teaching experience with young professionals like those in our program. Must have experience with R and some knowledge of data science.

Hours per week: 10 - 15

Specific duties & responsibilities:

- Assist the teaching of the curriculum in conjunction with lead instructor in office hours each week.
- Host weekly one on one tutoring sessions with our students.
- Coordinate with the program administrator, lead instructor, and other tutors to help coordinate the support the DataTrail students
- Willing to build up programming/data science knowledge as needed for teaching our DataTrail scholars.
- Familiarity with R required.
- Familiarity with GitHub preferred.
```

## Step 4: Finding the scholars

This is something your Program Administrator and Case Manager will coordinate with your community non-profit partner.

TODO: Have Liz write about her process.

Additionally, there is an open 

## Step 5: Setting up to run your first cohort

## Step 6: Internships placements
